---
title: "Train a classifier for DeePlexiCon & Poreplex Dataset"
author: "Chao Tang"
date: 'Report created: `r Sys.Date()`'
output: 
  html_document: 
    code_folding: "hide"
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = 'center')
```

```{r}
library(caret)
library(doParallel)
cl <- makePSOCKcluster(10)
registerDoParallel(cl)

fitControl <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10)
```

# Poreplex

```{r}
TrainingData <- readRDS(file = "/mnt/raid5/Personal/tangchao/project/Nanopore/BarcodeDecomplex/analysis/06.DecodingDeePlexiConAndPoreplex/00.ModelTraining2/00.RData/Poreplex_TrainingSet.Rds")
```

```{r}
set.seed(9560)
TrainingData <- downSample(x = TrainingData[, -ncol(TrainingData)],
                           y = TrainingData$Class)
table(TrainingData$Class)
gc()
```

```{r}
set.seed(825)
Fit1 <- train(Class ~ ., data = TrainingData,
              preProc = c("center", "scale", "YeoJohnson", "nzv"),
              method = "rf",
              trControl = fitControl,
              verbose = FALSE,
              # to evaluate:
              # tuneGrid = expand.grid(mtry = 2),
              tuneLength = 1,
              metric = "Accuracy",
              allowParallel = TRUE)
save(Fit1, file = "/mnt/raid5/Personal/tangchao/project/Nanopore/BarcodeDecomplex/analysis/06.DecodingDeePlexiConAndPoreplex/00.ModelTraining2/01.Model/Poreplex_Classifier.RData")
stopCluster(cl)
```

# DeePlexiCon

```{r}
TrainingData <- readRDS(file = "/mnt/raid5/Personal/tangchao/project/Nanopore/BarcodeDecomplex/analysis/06.DecodingDeePlexiConAndPoreplex/00.ModelTraining2/00.RData/DeePlexiCon_TrainingSet.Rds")
```

```{r}
set.seed(9560)
TrainingData <- downSample(x = TrainingData[, -ncol(TrainingData)],
                           y = TrainingData$Class)
table(TrainingData$Class)
gc()
```

```{r}
set.seed(825)
Fit1 <- train(Class ~ ., data = TrainingData,
              preProc = c("center", "scale", "YeoJohnson", "nzv"),
              method = "rf",
              trControl = fitControl,
              verbose = FALSE,
              # to evaluate:
              # tuneGrid = expand.grid(mtry = 2),
              tuneLength = 5,
              metric = "Accuracy",
              allowParallel = TRUE)
save(Fit1, file = "/mnt/raid5/Personal/tangchao/project/Nanopore/BarcodeDecomplex/analysis/06.DecodingDeePlexiConAndPoreplex/00.ModelTraining2/01.Model/DeePlexiCon_Classifier.RData")
stopCluster(cl)
```
